export const infoPlans = [
  {
    title: "Classic",
    price: 49.99,
    currency: "USD",
    frequency: "/month",
    description: "The essential health plan.",
    features: [
      "Personalized healthcare service.",
      "Available for single individuals or those seeking individualized medical care.",
      "Exclusive medical history records for the user.",
      "Access to personalized health tracking.",
      "Medical care focused on individual well-being.",
      "Option to choose your own primary care physician.",
      "Flexible appointment scheduling to accommodate individual schedules.",
    ],
    cta: "Start your trial",
    mostPopular: true,
  },
  {
    title: "Family",
    price: 89.99,
    currency: "USD",
    frequency: "/month",
    description: "The family health plan.",
    features: [
      "Designed to cater to the entire family under a single plan.",
      "Medical consultations available for all family members.",
      "Sharing of medical records for better coordination among family members.",
      "Joint appointment scheduling to facilitate care for multiple family members.",
      "Increased convenience by having all loved ones under one plan.",
      "Benefits for all ages and family health needs.",
    ],
    cta: "Start your trial",
    mostPopular: false,
  },
];
